# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRRy7DVYso0n4apETwoOFcP15zS1A302
"""

import pandas as pd
baza={
    "FISH":["Qadamova Zulayho","Xalilov Durbek"],
    "Manzili":["Farg'ona shaxar","Farg'ona shaxar"],
    "Yoshi":["28","68"],
    "Ish joyi":["TATUFF","TATUFF"],
    "Jinsi":["ayol","erkak"]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)